### ISSUE TITLE
Recommendation: Simplify CSS

### ISSUE THREAD

**Issue by melissamcewen** [MoltenBlue/prj-rev-bwfs-tea-cozy#2]
So when writing CSS it's worth looking for patterns in both
* the spec/design
* and in the CSS you write

Look for things in common, and think if there is a CSS rule that could apply to multiple things

Like here in your code:
```css
.location-one {
  display: flex;
  flex-direction: column;
  width: 300px;
  height: 250px;
  padding-top: 15px;
  padding-right: 40px;
  align-content: center;
}

.location-two {
  display: flex;
  flex-direction: column;
  width: 300px;
  height: 250px;
  padding-top: 15px;
  padding-right: 40px;
  padding-left: 40px;
  align-content: center;
}

.location-three {
  display: flex;
  flex-direction: column;
  width: 300px;
  height: 250px;
  padding-top: 15px;
  padding-left: 40px;
  align-content: center;
}
```

All these rules are the same, so you can make one rule

```css
.location {
  display: flex;
  flex-direction: column;
  width: 300px;
  height: 250px;
  padding-top: 15px;
  padding-right: 40px;
  align-content: center;
}

```

and apply it to all of them

```html
      <div class="locations">
          <div class="location">
            <h3>Downtown</h3>
            <h4>384 West 4th Street</h4>
            <h4>Suite 108</h4>
            <h4>Portland, Maine</h4>
          </div>
          <div class="location">
            <h3>East Bayside</h3>
            <h4>3433 Phisherman's Avenue</h4>
            <h4>(Northwest Corner)</h4>
            <h4>Portland, Maine</h4>
          </div>
          <div class="location">
            <h3>Oakdale</h3>
            <h4>515 Crescent Avenue</h4>
            <h4>Second Floor</h4>
            <h4>Portland, Maine</h4>
          </div>
        </div>
```
